spring:
  datasource:
    password: 1234
    url: jdbc:mysql://localhost:3306/casco
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  flyway:
    url: jdbc:mysql://localhost:3306/casco
    user: root
    password: 1234
    locations: db/migrations

server:
  error:
    include-message: always